### PR TITLE
make fax_config_readable

### PR DESCRIPTION
**Pull request by jorana**
I wanted to check the nT config for the size of the TPC, this PR puts it in a readable form so that people can check if the parameters are right.

At the moment we still have to (at least) update:
```
  "tpc_length": 96.9,
  "tpc_radius": 47.9,
```
I'm trying to find the right values but haven't succeeded yet.

### CODE REVIEW

**Comment by zhut19** [comment]
Good point, however, there are too many unnecessary columns in this config. @petergaemers I think your last two uploads overwrite the previously [cleaned-up version](https://github.com/XENONnT/strax_auxiliary_files/blob/ea385a945fbfe4ea15ab3e154c6a270ccccc97e9/fax_files/fax_config_nt.json). Would you mind recover that and reapply the changes you made later on?

**Comment by petergaemers** [comment]
The nt config now has the correct radius and length values.

**Comment by jorana** [comment]
@petergaemers , I'd propose to merge this one as it allows people to use git effectively. Now any changes are close to impossible to figure out.

**Comment by zhut19** [comment]
Sorry I deleted some of the keys hope nothing you @petergaemers are using got removed. Anyway, feel free to add them back.

I will use the sort_keys and indent so that the file looks nicer
json.dump(config, f, sort_keys=True, indent=4)

**Pull request merged**
