### PR TITLE
Sim update

### PR DESCRIPTION
**Pull request by zhut19**
Improve simulation config readability and include extra fields used in WFSim.

### CODE REVIEW

**Comment by jorana** [comment]
Thanks Tianyu, @ramirezdiego can you approve?

**Review by jorana — APPROVED** [review]

**Review by ramirezdiego — APPROVED** [review]
Ah, great! 👌 Thanks @zhut19, looks good.

**Comment by ramirezdiego** [comment]
@jorana I just fixed a couple of values to match the 1T conditions. I think we're now ready to merge.

**Comment by jorana** [comment]
Thanks Diego!

**Pull request merged**
